chromatic-protocol/liquidity-provider

.github/workflows/pr-sdk.yml
=> add action of pr to sdk

.github/workflows/pr-sdk.yml
=> feat(ci): add pr action to `liquidity-provider-tasks` repo #26

contracts/lp/base/ChromaticLPLogicBase.sol
=> add `verifyCallback` to all callback

contracts/lp/ChromaticLPLogic.sol, contracts/lp/ChromaticLPRegistry.sol, contracts/lp/base/ChromaticLPBase.sol, contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/base/ChromaticLPStorageCore.sol, contracts/lp/libraries/LPStateLogic.sol
=> fix: slither alerts

contracts/lp/libraries/LPState.sol, contracts/lp/libraries/LPStateLogic.sol
=> remove redundunt `providerMap`

contracts/lp/base/ChromaticLPLogicBase.sol
=> fix: `cancelSettleTask` #40

contracts/lp/base/ChromaticLPLogicBase.sol
=> fix duplicated reentrancy check when rebalancing

package.json, yarn.lock
=> bump openzepplin/contract

contracts/lp/libraries/LPStateValue.sol
=> fix utilization

contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/libraries/LPStateLogic.sol
=> fix rebalance

contracts/lp/ChromaticLP.sol, contracts/lp/base/ChromaticLPBase.sol, contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/base/ChromaticLPStorageCore.sol, contracts/lp/interfaces/IChromaticLPAdmin.sol, contracts/lp/libraries/Errors.sol, contracts/lp/libraries/LPConfig.sol, contracts/lp/libraries/LPStateLogic.sol, deploy/1_deploy_lp_all.ts, hardhat/common/types.ts, hardhat/repl/index.ts, test/forge/lp/ChromaticLP.t.sol
=> set minimal cost for automation

contracts/lp/ChromaticLP.sol, contracts/lp/interfaces/IChromaticLPErrors.sol, contracts/lp/interfaces/IChromaticLPMeta.sol, contracts/lp/libraries/LPState.sol, contracts/lp/libraries/LPStateLogic.sol, contracts/lp/libraries/LPStateSetup.sol, deploy/1_deploy_lp_all.ts, hardhat/common/DeployTool.ts, hardhat/common/DeployedStore.ts, hardhat/common/Helper.ts, hardhat/common/LPConfig.ts, hardhat/common/types.ts, hardhat/repl/Client.ts, hardhat/repl/index.ts
=> update LP config and deploy multi LPs per market

subgraph/schema.graphql, subgraph/src/chromatic-lp.ts
=> fix: save DB insert time for lp events #66

subgraph/abis/ChromaticLPRegistry.json
=> chore: deploy subgraph #69

subgraph/schema.graphql, subgraph/src/chromatic-lp.ts
=> fix: remove `insertedAt` #73

contracts/lp/ChromaticLP.sol, contracts/lp/base/ChromaticLPBase.sol, contracts/lp/interfaces/IChromaticLPAdmin.sol, contracts/lp/interfaces/IChromaticLPMeta.sol
=> fix `Local variable shadowing`

yarn.lock
=> fix broken gh-action

hardhat/common/LPConfig.ts
=> chore: fix typo

contracts/lp/base/ChromaticLPLogicBase.sol
=> fix reentrancy in cancelTask

contracts/lp/ChromaticLP.sol, contracts/lp/base/ChromaticLPBase.sol, contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/base/ChromaticLPStorage.sol, contracts/lp/base/ChromaticLPStorageCore.sol, contracts/lp/interfaces/IChromaticLPAdmin.sol, contracts/lp/interfaces/IChromaticLPConfigLens.sol, contracts/lp/interfaces/IChromaticLPErrors.sol, contracts/lp/interfaces/IChromaticLPLiquidity.sol, contracts/lp/libraries/LPConfig.sol, hardhat/common/LPConfig.ts, hardhat/common/types.ts
=> feat: add minimum amount of addLiquidity

hardhat/common/DeployTool.ts, hardhat/common/Helper.ts, hardhat/common/LPConfig.ts, hardhat/common/types.ts
=> update default liquidity

hardhat.repl.config.ts, hardhat/tasks/index.ts, hardhat/tasks/list-unregistered-lp.ts, hardhat/tasks/remove-liquidity-unregistered.ts, package.json
=> chore: tasks for management

subgraph/abis/IChromaticLP.json
=> chore: deploy subgraph #111

.github/workflows/pr-sdk.yml
=> ci: change pr branch #114

subgraph/abis/ChromaticBPFactory.json, subgraph/abis/IChromaticBP.json, subgraph/abis/IChromaticLP.json, subgraph/schema.graphql, subgraph/scripts/prepare.mjs, subgraph/src/chromatic-bp-factory.ts, subgraph/src/chromatic-bp.ts, subgraph/subgraph.template.yaml
=> feat: add `BPDeposited`, `BPExecuted` handler #118

contracts/bp/ChromaticBP.sol, contracts/lp/ChromaticLP.sol, contracts/lp/ChromaticLPLogic.sol, contracts/lp/base/ChromaticLPLogicBase.sol, hardhat/common/Contracts.ts, hardhat/common/LPConfig.ts
=> Fixe: cancelTask if manually executed (LP/BP)

subgraph/abis/IChromaticBP.json, subgraph/abis/IChromaticLP.json, subgraph/abis/IChromaticMarket.json, subgraph/abis/IERC20Metadata.json, subgraph/abis/IOracleProvider.json, subgraph/schema.graphql, subgraph/scripts/prepare.mjs, subgraph/src/chromatic-bp.ts, subgraph/src/chromatic-lp-registry.ts, subgraph/subgraph.template.yaml
=> feat: add `ChromaticLP` enitity into subgraph

subgraph/abis/ChromaticLP.json, subgraph/schema.graphql, subgraph/scripts/prepare.mjs, subgraph/src/chromatic-lp-registry.ts, subgraph/src/chromatic-lp.ts, subgraph/subgraph.template.yaml
=> add ChromaticLP schema field

subgraph/abis/ChromaticBP.json, subgraph/schema.graphql, subgraph/scripts/prepare.mjs, subgraph/src/chromatic-bp-factory.ts, subgraph/src/chromatic-bp.ts, subgraph/subgraph.template.yaml
=> feat: add `ChromaticBP` into subgraph Fixes #145

contracts/lp/ChromaticLPLogic.sol, contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/libraries/LPStateLogic.sol, contracts/mocks/FixedPriceSwapRouter.sol, contracts/mocks/GelatoLiquidatorMock.sol, contracts/mocks/TestSettlementToken.sol, test/forge/BaseSetup.sol, test/forge/lp/ChromaticLP.t.sol
=> fix: rebalance

contracts/automation/mate2/AutomateLP.sol, contracts/lp/ChromaticLP.sol, contracts/lp/base/ChromaticLPBase.sol, contracts/lp/base/SuspendMode.sol, contracts/lp/interfaces/IChromaticLPAdmin.sol, contracts/lp/interfaces/IChromaticLPErrors.sol, contracts/lp/interfaces/IChromaticLPEvents.sol
=> feat: add suspend mode

contracts/lp/base/ChromaticLPBase.sol, contracts/lp/base/Privatable.sol, contracts/lp/interfaces/IChromaticLPAdmin.sol, contracts/lp/interfaces/IChromaticLPErrors.sol, contracts/lp/interfaces/IChromaticLPEvents.sol
=> feat: private/public mode

hardhat/common/DeployTool.ts
=> chore: add script to add liquidity for all registered LP

contracts/automation/mate2/AutomateBP.sol, contracts/automation/mate2/AutomateLP.sol
=> fix: mutable upkeep gaslimit

contracts/bp/ChromaticBP.sol
=> fix: `BPFullyRaised` condition

yarn.lock
Reverts chromatic-protocol/liquidity-provider#163
=> Revert "chore(deps): bump undici from 5.24.0 to 5.28.2"

subgraph/abis/ChromaticBPFactory.json
=> chore: update abis for subgraph

contracts/bp/ChromaticBP.sol
=> fix: approve when boosting

contracts/automation/mate2/AutomateBP.sol, contracts/automation/mate2/AutomateLP.sol
=> chore: update default gaslimit

contracts/automation/gelato/AutomateBP.sol, contracts/automation/gelato/AutomateLP.sol, contracts/automation/gelato/interfaces/IAutomateGelatoBP.sol, contracts/automation/gelato/interfaces/IAutomateGelatoLP.sol, contracts/automation/mate2/AutomateBP.sol, contracts/automation/mate2/AutomateLP.sol, contracts/automation/mate2/interfaces/IAutomateMate2BP.sol, contracts/automation/mate2/interfaces/IAutomateMate2LP.sol, contracts/bp/ChromaticBP.sol, contracts/bp/ChromaticBPFactory.sol, contracts/bp/interfaces/IChromaticBP.sol, contracts/bp/interfaces/IChromaticBPAdmin.sol, contracts/bp/interfaces/IChromaticBPErrors.sol, contracts/bp/interfaces/IChromaticBPEvents.sol, contracts/bp/interfaces/IChromaticBPFactory.sol, contracts/bp/interfaces/IChromaticBPLens.sol, contracts/bp/libraries/BPState.sol, contracts/lp/ChromaticCommonLP.sol, contracts/lp/interfaces/IChromaticLPAutomate.sol
=> feat: add `cancelBP` by DAO

test/forge/bp/ChromaticBP.t.sol
=> feat: add test of deposit

contracts/automation/gelato/AutomateLP.sol, contracts/automation/gelato/interfaces/IAutomateGelatoLP.sol
=> refactor: `cancelUpkeep` in `IAutomateGelatoLP`

subgraph/abis/ChromaticBP.json, subgraph/abis/ChromaticBPFactory.json, subgraph/abis/ChromaticLP.json, subgraph/abis/ChromaticLPRegistry.json, subgraph/abis/IChromaticMarket.json, subgraph/schema.graphql, subgraph/src/chromatic-bp.ts, subgraph/subgraph.template.yaml
=> fix: update subgraph #195

contracts/bp/ChromaticBP.sol, contracts/bp/interfaces/IChromaticBPErrors.sol, contracts/bp/interfaces/IChromaticBPLens.sol, contracts/bp/libraries/BPConfig.sol, contracts/lp/base/ChromaticLPBase.sol, deploy/5_deploy_bp.ts
=> feat: add `minDeposit` in BP

subgraph/abis/ChromaticBPFactory.json, subgraph/abis/IChromaticMarket.json
=> chore: deploy subgraph

subgraph/schema.graphql, subgraph/src/chromatic-bp-factory.ts
=> fix: add `minDeposit` field into `ChromaticBP` entity

contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/libraries/LPStateLogic.sol, test/forge/BaseSetup.sol, test/forge/bp/ChromaticBP.t.sol, test/forge/lp/ChromaticLP.t.sol, test/forge/lp/Helper.sol
=> fix: not available `LpReceipts` in `withdrawLiquidityBatchCallback`

package.json, test/forge/BaseSetup.sol, test/forge/lp/ChromaticLP.t.sol, yarn.lock
=> chore: bump `contracts`

wagmi.config.ts
=> fix: publish addresse of arbitrum_one

contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/interfaces/IChromaticLPLogic.sol
=> chore: set `version` of LPlogic in ctor

contracts/lp/ChromaticLPLogic.sol, contracts/lp/base/ChromaticLPLogicBase.sol, contracts/lp/interfaces/IChromaticLPErrors.sol, contracts/lp/libraries/Constants.sol, contracts/lp/libraries/LPStateLogic.sol, test/forge/BaseSetup.sol, test/forge/lp/ChromaticLPToken.t.sol, test/forge/lp/ChromaticLPUpgrade.t.sol, test/forge/lp/LPHelper.sol, test/forge/lp/fix20240222/ChromaticLP20240222.t.sol
=> fix: addLiquidity wit checking MIN_ADD_LIQUIDITY_BIN and exclude zero amount of bins when removeLiquidity

contracts/automation/gelato/AutomateBP.sol, contracts/automation/mate2/AutomateBP.sol, contracts/bp/interfaces/IAutomateBP.sol
=> fix: update `cancelBoostTask` modifier to owner or BP
